// 214 Kangxi Radicals data (from branneman's JSON)
const RADICALS = [
    { id: 1, radical: "一", pinyin: "yī", english: "one", strokeCount: 1 },
    { id: 2, radical: "丨", pinyin: "gǔn", english: "line", strokeCount: 1 },
    { id: 3, radical: "丶", pinyin: "zhǔ", english: "dot", strokeCount: 1 },
    { id: 4, radical: "丿", pinyin: "piě", english: "slash", strokeCount: 1 },
    { id: 5, radical: "乙", pinyin: "yǐ", english: "second", strokeCount: 1 },
    { id: 6, radical: "亅", pinyin: "jué", english: "hook", strokeCount: 1 },
    { id: 7, radical: "二", pinyin: "èr", english: "two", strokeCount: 2 },
    { id: 8, radical: "亠", pinyin: "tóu", english: "lid", strokeCount: 2 },
    { id: 9, radical: "人", pinyin: "rén", english: "man", strokeCount: 2 },
    { id: 10, radical: "儿", pinyin: "ér", english: "legs", strokeCount: 2 },
    { id: 11, radical: "入", pinyin: "rù", english: "enter", strokeCount: 2 },
    { id: 12, radical: "八", pinyin: "bā", english: "eight", strokeCount: 2 },
    { id: 13, radical: "冂", pinyin: "jiōng", english: "down box", strokeCount: 2 },
    { id: 14, radical: "冖", pinyin: "mì", english: "cover", strokeCount: 2 },
    { id: 15, radical: "冫", pinyin: "bīng", english: "ice", strokeCount: 2 },
    { id: 16, radical: "几", pinyin: "jī", english: "table", strokeCount: 2 },
    { id: 17, radical: "凵", pinyin: "qiǎn", english: "open box", strokeCount: 2 },
    { id: 18, radical: "刀", pinyin: "dāo", english: "knife", strokeCount: 2 },
    { id: 19, radical: "力", pinyin: "lì", english: "power", strokeCount: 2 },
    { id: 20, radical: "勹", pinyin: "bāo", english: "wrap", strokeCount: 2 },
    { id: 21, radical: "匕", pinyin: "bǐ", english: "spoon", strokeCount: 2 },
    { id: 22, radical: "匚", pinyin: "fāng", english: "box", strokeCount: 2 },
    { id: 23, radical: "匸", pinyin: "xǐ", english: "hiding", strokeCount: 2 },
    { id: 24, radical: "十", pinyin: "shí", english: "ten", strokeCount: 2 },
    { id: 25, radical: "卜", pinyin: "bǔ", english: "divination", strokeCount: 2 },
    { id: 26, radical: "卩", pinyin: "jié", english: "seal", strokeCount: 2 },
    { id: 27, radical: "厂", pinyin: "hàn", english: "cliff", strokeCount: 2 },
    { id: 28, radical: "厶", pinyin: "sī", english: "private", strokeCount: 2 },
    { id: 29, radical: "又", pinyin: "yòu", english: "again", strokeCount: 2 },
    { id: 30, radical: "口", pinyin: "kǒu", english: "mouth", strokeCount: 3 },
    { id: 31, radical: "囗", pinyin: "wéi", english: "enclosure", strokeCount: 3 },
    { id: 32, radical: "土", pinyin: "tǔ", english: "earth", strokeCount: 3 },
    { id: 33, radical: "士", pinyin: "shì", english: "scholar", strokeCount: 3 },
    { id: 34, radical: "夂", pinyin: "zhǐ", english: "go", strokeCount: 3 },
    { id: 35, radical: "夊", pinyin: "suī", english: "go slowly", strokeCount: 3 },
    { id: 36, radical: "夕", pinyin: "xī", english: "evening", strokeCount: 3 },
    { id: 37, radical: "大", pinyin: "dà", english: "big", strokeCount: 3 },
    { id: 38, radical: "女", pinyin: "nǚ", english: "woman", strokeCount: 3 },
    { id: 39, radical: "子", pinyin: "zǐ", english: "child", strokeCount: 3 },
    { id: 40, radical: "宀", pinyin: "mián", english: "roof", strokeCount: 3 },
    { id: 41, radical: "寸", pinyin: "cùn", english: "inch", strokeCount: 3 },
    { id: 42, radical: "小", pinyin: "xiǎo", english: "small", strokeCount: 3 },
    { id: 43, radical: "尢", pinyin: "wāng", english: "lame", strokeCount: 3 },
    { id: 44, radical: "尸", pinyin: "shī", english: "corpse", strokeCount: 3 },
    { id: 45, radical: "屮", pinyin: "chè", english: "sprout", strokeCount: 3 },
    { id: 46, radical: "山", pinyin: "shān", english: "mountain", strokeCount: 3 },
    { id: 47, radical: "巛", pinyin: "chuān", english: "river", strokeCount: 3 },
    { id: 48, radical: "工", pinyin: "gōng", english: "work", strokeCount: 3 },
    { id: 49, radical: "己", pinyin: "jǐ", english: "oneself", strokeCount: 3 },
    { id: 50, radical: "巾", pinyin: "jīn", english: "turban", strokeCount: 3 },
    { id: 51, radical: "干", pinyin: "gān", english: "dry", strokeCount: 3 },
    { id: 52, radical: "幺", pinyin: "yāo", english: "short thread", strokeCount: 3 },
    { id: 53, radical: "广", pinyin: "guǎng", english: "dotted cliff", strokeCount: 3 },
    { id: 54, radical: "廴", pinyin: "yǐn", english: "long stride", strokeCount: 3 },
    { id: 55, radical: "廾", pinyin: "gǒng", english: "two hands", strokeCount: 3 },
    { id: 56, radical: "弋", pinyin: "yì", english: "shoot", strokeCount: 3 },
    { id: 57, radical: "弓", pinyin: "gōng", english: "bow", strokeCount: 3 },
    { id: 58, radical: "彐", pinyin: "jì", english: "snout", strokeCount: 3 },
    { id: 59, radical: "彡", pinyin: "shān", english: "bristle", strokeCount: 3 },
    { id: 60, radical: "彳", pinyin: "chì", english: "step", strokeCount: 3 },
    { id: 61, radical: "心", pinyin: "xīn", english: "heart", strokeCount: 4 },
    { id: 62, radical: "戈", pinyin: "gē", english: "halberd", strokeCount: 4 },
    { id: 63, radical: "戶", pinyin: "hù", english: "door", strokeCount: 4 },
    { id: 64, radical: "手", pinyin: "shǒu", english: "hand", strokeCount: 4 },
    { id: 65, radical: "支", pinyin: "zhī", english: "branch", strokeCount: 4 },
    { id: 66, radical: "攴", pinyin: "pū", english: "rap", strokeCount: 4 },
    { id: 67, radical: "文", pinyin: "wén", english: "script", strokeCount: 4 },
    { id: 68, radical: "斗", pinyin: "dǒu", english: "dipper", strokeCount: 4 },
    { id: 69, radical: "斤", pinyin: "jīn", english: "axe", strokeCount: 4 },
    { id: 70, radical: "方", pinyin: "fāng", english: "square", strokeCount: 4 },
    { id: 71, radical: "无", pinyin: "wú", english: "not", strokeCount: 4 },
    { id: 72, radical: "日", pinyin: "rì", english: "sun", strokeCount: 4 },
    { id: 73, radical: "曰", pinyin: "yuē", english: "say", strokeCount: 4 },
    { id: 74, radical: "月", pinyin: "yuè", english: "moon", strokeCount: 4 },
    { id: 75, radical: "木", pinyin: "mù", english: "tree", strokeCount: 4 },
    { id: 76, radical: "欠", pinyin: "qiàn", english: "lack", strokeCount: 4 },
    { id: 77, radical: "止", pinyin: "zhǐ", english: "stop", strokeCount: 4 },
    { id: 78, radical: "歹", pinyin: "dǎi", english: "death", strokeCount: 4 },
    { id: 79, radical: "殳", pinyin: "shū", english: "weapon", strokeCount: 4 },
    { id: 80, radical: "毋", pinyin: "wú", english: "do not", strokeCount: 4 },
    { id: 81, radical: "比", pinyin: "bǐ", english: "compare", strokeCount: 4 },
    { id: 82, radical: "毛", pinyin: "máo", english: "fur", strokeCount: 4 },
    { id: 83, radical: "氏", pinyin: "shì", english: "clan", strokeCount: 4 },
    { id: 84, radical: "气", pinyin: "qì", english: "steam", strokeCount: 4 },
    { id: 85, radical: "水", pinyin: "shuǐ", english: "water", strokeCount: 4 },
    { id: 86, radical: "火", pinyin: "huǒ", english: "fire", strokeCount: 4 },
    { id: 87, radical: "爪", pinyin: "zhǎo", english: "claw", strokeCount: 4 },
    { id: 88, radical: "父", pinyin: "fù", english: "father", strokeCount: 4 },
    { id: 89, radical: "爻", pinyin: "yáo", english: "trigrams", strokeCount: 4 },
    { id: 90, radical: "爿", pinyin: "pán", english: "split wood", strokeCount: 4 },
    { id: 91, radical: "片", pinyin: "piàn", english: "slice", strokeCount: 4 },
    { id: 92, radical: "牙", pinyin: "yá", english: "fang", strokeCount: 4 },
    { id: 93, radical: "牛", pinyin: "niú", english: "cow", strokeCount: 4 },
    { id: 94, radical: "犬", pinyin: "quǎn", english: "dog", strokeCount: 4 },
    { id: 95, radical: "玄", pinyin: "xuán", english: "profound", strokeCount: 5 },
    { id: 96, radical: "玉", pinyin: "yù", english: "jade", strokeCount: 5 },
    { id: 97, radical: "瓜", pinyin: "guā", english: "melon", strokeCount: 5 },
    { id: 98, radical: "瓦", pinyin: "wǎ", english: "tile", strokeCount: 5 },
    { id: 99, radical: "甘", pinyin: "gān", english: "sweet", strokeCount: 5 },
    { id: 100, radical: "生", pinyin: "shēng", english: "life", strokeCount: 5 },
    { id: 101, radical: "用", pinyin: "yòng", english: "use", strokeCount: 5 },
    { id: 102, radical: "田", pinyin: "tián", english: "field", strokeCount: 5 },
    { id: 103, radical: "疋", pinyin: "pǐ", english: "bolt of cloth", strokeCount: 5 },
    { id: 104, radical: "疒", pinyin: "nè", english: "sickness", strokeCount: 5 },
    { id: 105, radical: "癶", pinyin: "bō", english: "footsteps", strokeCount: 5 },
    { id: 106, radical: "白", pinyin: "bái", english: "white", strokeCount: 5 },
    { id: 107, radical: "皮", pinyin: "pí", english: "skin", strokeCount: 5 },
    { id: 108, radical: "皿", pinyin: "mǐn", english: "dish", strokeCount: 5 },
    { id: 109, radical: "目", pinyin: "mù", english: "eye", strokeCount: 5 },
    { id: 110, radical: "矛", pinyin: "máo", english: "spear", strokeCount: 5 },
    { id: 111, radical: "矢", pinyin: "shǐ", english: "arrow", strokeCount: 5 },
    { id: 112, radical: "石", pinyin: "shí", english: "stone", strokeCount: 5 },
    { id: 113, radical: "示", pinyin: "shì", english: "spirit", strokeCount: 5 },
    { id: 114, radical: "禸", pinyin: "róu", english: "track", strokeCount: 5 },
    { id: 115, radical: "禾", pinyin: "hé", english: "grain", strokeCount: 5 },
    { id: 116, radical: "穴", pinyin: "xué", english: "cave", strokeCount: 5 },
    { id: 117, radical: "立", pinyin: "lì", english: "stand", strokeCount: 5 },
    { id: 118, radical: "竹", pinyin: "zhú", english: "bamboo", strokeCount: 6 },
    { id: 119, radical: "米", pinyin: "mǐ", english: "rice", strokeCount: 6 },
    { id: 120, radical: "糸", pinyin: "mì", english: "silk", strokeCount: 6 },
    { id: 121, radical: "缶", pinyin: "fǒu", english: "jar", strokeCount: 6 },
    { id: 122, radical: "网", pinyin: "wǎng", english: "net", strokeCount: 6 },
    { id: 123, radical: "羊", pinyin: "yáng", english: "sheep", strokeCount: 6 },
    { id: 124, radical: "羽", pinyin: "yǔ", english: "feather", strokeCount: 6 },
    { id: 125, radical: "老", pinyin: "lǎo", english: "old", strokeCount: 6 },
    { id: 126, radical: "而", pinyin: "ér", english: "and", strokeCount: 6 },
    { id: 127, radical: "耒", pinyin: "lěi", english: "plow", strokeCount: 6 },
    { id: 128, radical: "耳", pinyin: "ěr", english: "ear", strokeCount: 6 },
    { id: 129, radical: "聿", pinyin: "yù", english: "brush", strokeCount: 6 },
    { id: 130, radical: "肉", pinyin: "ròu", english: "meat", strokeCount: 6 },
    { id: 131, radical: "臣", pinyin: "chén", english: "minister", strokeCount: 6 },
    { id: 132, radical: "自", pinyin: "zì", english: "self", strokeCount: 6 },
    { id: 133, radical: "至", pinyin: "zhì", english: "arrive", strokeCount: 6 },
    { id: 134, radical: "臼", pinyin: "jiù", english: "mortar", strokeCount: 6 },
    { id: 135, radical: "舌", pinyin: "shé", english: "tongue", strokeCount: 6 },
    { id: 136, radical: "舛", pinyin: "chuǎn", english: "oppose", strokeCount: 6 },
    { id: 137, radical: "舟", pinyin: "zhōu", english: "boat", strokeCount: 6 },
    { id: 138, radical: "艮", pinyin: "gèn", english: "stopping", strokeCount: 6 },
    { id: 139, radical: "色", pinyin: "sè", english: "color", strokeCount: 6 },
    { id: 140, radical: "艸", pinyin: "cǎo", english: "grass", strokeCount: 6 },
    { id: 141, radical: "虍", pinyin: "hū", english: "tiger", strokeCount: 6 },
    { id: 142, radical: "虫", pinyin: "chóng", english: "insect", strokeCount: 6 },
    { id: 143, radical: "血", pinyin: "xuè", english: "blood", strokeCount: 6 },
    { id: 144, radical: "行", pinyin: "xíng", english: "walk", strokeCount: 6 },
    { id: 145, radical: "衣", pinyin: "yī", english: "clothes", strokeCount: 6 },
    { id: 146, radical: "襾", pinyin: "yà", english: "west", strokeCount: 6 },
    { id: 147, radical: "見", pinyin: "jiàn", english: "see", strokeCount: 7 },
    { id: 148, radical: "角", pinyin: "jiǎo", english: "horn", strokeCount: 7 },
    { id: 149, radical: "言", pinyin: "yán", english: "speech", strokeCount: 7 },
    { id: 150, radical: "谷", pinyin: "gǔ", english: "valley", strokeCount: 7 },
    { id: 151, radical: "豆", pinyin: "dòu", english: "bean", strokeCount: 7 },
    { id: 152, radical: "豕", pinyin: "shǐ", english: "pig", strokeCount: 7 },
    { id: 153, radical: "豸", pinyin: "zhì", english: "badger", strokeCount: 7 },
    { id: 154, radical: "貝", pinyin: "bèi", english: "shell", strokeCount: 7 },
    { id: 155, radical: "赤", pinyin: "chì", english: "red", strokeCount: 7 },
    { id: 156, radical: "走", pinyin: "zǒu", english: "run", strokeCount: 7 },
    { id: 157, radical: "足", pinyin: "zú", english: "foot", strokeCount: 7 },
    { id: 158, radical: "身", pinyin: "shēn", english: "body", strokeCount: 7 },
    { id: 159, radical: "車", pinyin: "chē", english: "cart", strokeCount: 7 },
    { id: 160, radical: "辛", pinyin: "xīn", english: "bitter", strokeCount: 7 },
    { id: 161, radical: "辰", pinyin: "chén", english: "morning", strokeCount: 7 },
    { id: 162, radical: "辵", pinyin: "chuò", english: "walk", strokeCount: 7 },
    { id: 163, radical: "邑", pinyin: "yì", english: "city", strokeCount: 7 },
    { id: 164, radical: "酉", pinyin: "yǒu", english: "wine", strokeCount: 7 },
    { id: 165, radical: "釆", pinyin: "biàn", english: "distinguish", strokeCount: 7 },
    { id: 166, radical: "里", pinyin: "lǐ", english: "village", strokeCount: 7 },
    { id: 167, radical: "金", pinyin: "jīn", english: "gold", strokeCount: 8 },
    { id: 168, radical: "長", pinyin: "cháng", english: "long", strokeCount: 8 },
    { id: 169, radical: "門", pinyin: "mén", english: "gate", strokeCount: 8 },
    { id: 170, radical: "阜", pinyin: "fù", english: "mound", strokeCount: 8 },
    { id: 171, radical: "隶", pinyin: "lì", english: "slave", strokeCount: 8 },
    { id: 172, radical: "隹", pinyin: "zhuī", english: "short-tailed bird", strokeCount: 8 },
    { id: 173, radical: "雨", pinyin: "yǔ", english: "rain", strokeCount: 8 },
    { id: 174, radical: "靑", pinyin: "qīng", english: "blue", strokeCount: 8 },
    { id: 175, radical: "非", pinyin: "fēi", english: "wrong", strokeCount: 8 },
    { id: 176, radical: "面", pinyin: "miàn", english: "face", strokeCount: 9 },
    { id: 177, radical: "革", pinyin: "gé", english: "leather", strokeCount: 9 },
    { id: 178, radical: "韋", pinyin: "wéi", english: "tanned leather", strokeCount: 9 },
    { id: 179, radical: "韭", pinyin: "jiǔ", english: "leek", strokeCount: 9 },
    { id: 180, radical: "音", pinyin: "yīn", english: "sound", strokeCount: 9 },
    { id: 181, radical: "頁", pinyin: "yè", english: "leaf", strokeCount: 9 },
    { id: 182, radical: "風", pinyin: "fēng", english: "wind", strokeCount: 9 },
    { id: 183, radical: "飛", pinyin: "fēi", english: "fly", strokeCount: 9 },
    { id: 184, radical: "食", pinyin: "shí", english: "eat", strokeCount: 9 },
    { id: 185, radical: "首", pinyin: "shǒu", english: "head", strokeCount: 9 },
    { id: 186, radical: "香", pinyin: "xiāng", english: "fragrant", strokeCount: 9 },
    { id: 187, radical: "馬", pinyin: "mǎ", english: "horse", strokeCount: 10 },
    { id: 188, radical: "骨", pinyin: "gǔ", english: "bone", strokeCount: 10 },
    { id: 189, radical: "高", pinyin: "gāo", english: "tall", strokeCount: 10 },
    { id: 190, radical: "髟", pinyin: "biāo", english: "hair", strokeCount: 10 },
    { id: 191, radical: "鬥", pinyin: "dòu", english: "fight", strokeCount: 10 },
    { id: 192, radical: "鬯", pinyin: "chàng", english: "sacrificial wine", strokeCount: 10 },
    { id: 193, radical: "鬲", pinyin: "lì", english: "cauldron", strokeCount: 10 },
    { id: 194, radical: "鬼", pinyin: "guǐ", english: "ghost", strokeCount: 10 },
    { id: 195, radical: "魚", pinyin: "yú", english: "fish", strokeCount: 11 },
    { id: 196, radical: "鳥", pinyin: "niǎo", english: "bird", strokeCount: 11 },
    { id: 197, radical: "鹵", pinyin: "lǔ", english: "salt", strokeCount: 11 },
    { id: 198, radical: "鹿", pinyin: "lù", english: "deer", strokeCount: 11 },
    { id: 199, radical: "麥", pinyin: "mài", english: "wheat", strokeCount: 11 },
    { id: 200, radical: "麻", pinyin: "má", english: "hemp", strokeCount: 11 },
    { id: 201, radical: "黃", pinyin: "huáng", english: "yellow", strokeCount: 12 },
    { id: 202, radical: "黍", pinyin: "shǔ", english: "millet", strokeCount: 12 },
    { id: 203, radical: "黑", pinyin: "hēi", english: "black", strokeCount: 12 },
    { id: 204, radical: "黹", pinyin: "zhǐ", english: "embroidery", strokeCount: 12 },
    { id: 205, radical: "黽", pinyin: "mǐn", english: "frog", strokeCount: 13 },
    { id: 206, radical: "鼎", pinyin: "dǐng", english: "tripod", strokeCount: 13 },
    { id: 207, radical: "鼓", pinyin: "gǔ", english: "drum", strokeCount: 13 },
    { id: 208, radical: "鼠", pinyin: "shǔ", english: "rat", strokeCount: 13 },
    { id: 209, radical: "鼻", pinyin: "bí", english: "nose", strokeCount: 14 },
    { id: 210, radical: "齊", pinyin: "qí", english: "even", strokeCount: 14 },
    { id: 211, radical: "齒", pinyin: "chǐ", english: "tooth", strokeCount: 15 },
    { id: 212, radical: "龍", pinyin: "lóng", english: "dragon", strokeCount: 16 },
    { id: 213, radical: "龜", pinyin: "guī", english: "turtle", strokeCount: 16 },
    { id: 214, radical: "龠", pinyin: "yuè", english: "flute", strokeCount: 17 }
];

// Tone mark to base vowel + tone number mapping
const TONE_MARK_TO_BASE = {
    'ā': ['a', 1], 'á': ['a', 2], 'ǎ': ['a', 3], 'à': ['a', 4],
    'ē': ['e', 1], 'é': ['e', 2], 'ě': ['e', 3], 'è': ['e', 4],
    'ī': ['i', 1], 'í': ['i', 2], 'ǐ': ['i', 3], 'ì': ['i', 4],
    'ō': ['o', 1], 'ó': ['o', 2], 'ǒ': ['o', 3], 'ò': ['o', 4],
    'ū': ['u', 1], 'ú': ['u', 2], 'ǔ': ['u', 3], 'ù': ['u', 4],
    'ǖ': ['ü', 1], 'ǘ': ['ü', 2], 'ǚ': ['ü', 3], 'ǜ': ['ü', 4],
};

// Complete pinyin+tone combinations from GitHub repo (1,622 total)
const SYLLABLE_TONES = {
    'a': '1234', 'ai': '1234', 'an': '1234', 'ang': '1234', 'ao': '1234',
    'ba': '1234', 'bai': '1234', 'ban': '1234', 'bang': '1234', 'bao': '1234',
    'bei': '1234', 'ben': '1234', 'beng': '1234', 'bi': '1234', 'bian': '1234',
    'biao': '234', 'bie': '1234', 'bin': '1234', 'bing': '1234', 'bo': '1234', 'bu': '1234',
    'ca': '1234', 'cai': '1234', 'can': '1234', 'cang': '1234', 'cao': '1234',
    'ce': '1234', 'cen': '1234', 'ceng': '1234', 'cha': '1234', 'chai': '1234',
    'chan': '1234', 'chang': '1234', 'chao': '1234', 'che': '1234', 'chen': '1234',
    'cheng': '1234', 'chi': '1234', 'chong': '1234', 'chou': '1234', 'chu': '1234',
    'chua': '1234', 'chuai': '1234', 'chuan': '1234', 'chuang': '1234', 'chui': '1234',
    'chun': '1234', 'chuo': '1234', 'ci': '1234', 'cong': '1234', 'cou': '1234',
    'cu': '1234', 'cuan': '1234', 'cui': '1234', 'cun': '1234', 'cuo': '134',
    'da': '1234', 'dai': '1234', 'dan': '1234', 'dang': '1234', 'dao': '1234',
    'de': '1234', 'dei': '1234', 'den': '1234', 'deng': '1234', 'di': '1234',
    'dian': '1234', 'diang': '234', 'diao': '234', 'die': '1234', 'ding': '1234',
    'diu': '1234', 'dong': '1234', 'dou': '1234', 'du': '1234', 'duan': '1234',
    'dui': '1234', 'dun': '1234', 'duo': '1234',
    'e': '1234', 'ei': '1234', 'en': '1234', 'er': '1234',
    'fa': '1234', 'fan': '1234', 'fang': '1234', 'fei': '1234', 'fen': '1234',
    'feng': '1234', 'fo': '1234', 'fou': '1234', 'fu': '1234',
    'ga': '1234', 'gai': '1234', 'gan': '1234', 'gang': '1234', 'gao': '1234',
    'ge': '1234', 'gei': '1234', 'gen': '1234', 'geng': '1234', 'gong': '1234',
    'gou': '1234', 'gu': '1234', 'gua': '1234', 'guai': '1234', 'guan': '1234',
    'guang': '1234', 'gui': '1234', 'gun': '1234', 'guo': '1234',
    'ha': '1234', 'hai': '1234', 'han': '1234', 'hang': '1234', 'hao': '1234',
    'he': '1234', 'hei': '1234', 'hen': '1234', 'heng': '1234', 'hong': '1234',
    'hou': '1234', 'hu': '1234', 'hua': '1234', 'huai': '1234', 'huan': '1234',
    'huang': '1234', 'hui': '1234', 'hun': '1234', 'huo': '1234',
    'ji': '1234', 'jia': '1234', 'jian': '1234', 'jiang': '1234', 'jiao': '1234',
    'jie': '1234', 'jin': '1234', 'jing': '134', 'jiong': '1234', 'jiu': '1234',
    'ju': '1234', 'juan': '1234', 'jue': '1234', 'jun': '1234',
    'ka': '1234', 'kai': '1234', 'kan': '1234', 'kang': '124', 'kao': '1234',
    'ke': '1234', 'ken': '1234', 'keng': '1234', 'kong': '1234', 'kou': '1234',
    'ku': '1234', 'kua': '1234', 'kuai': '1234', 'kuan': '1234', 'kuang': '1234',
    'kui': '1234', 'kun': '1234', 'kuo': '1234',
    'la': '1234', 'lai': '1234', 'lan': '1234', 'lang': '1234', 'lao': '1234',
    'le': '1234', 'lei': '1234', 'leng': '1234', 'li': '1234', 'lia': '1234',
    'lian': '1234', 'liang': '1234', 'liao': '1234', 'lie': '1234', 'lin': '234',
    'ling': '1234', 'liu': '1234', 'lo': '1234', 'long': '1234', 'lou': '1234',
    'lu': '1234', 'luan': '1234', 'lun': '234', 'luo': '1234',
    'luu': '1234', 'luue': '1234', 'luun': '234',
    'ma': '1234', 'mai': '1234', 'man': '1234', 'mang': '1234', 'mao': '1234',
    'me': '1234', 'mei': '1234', 'men': '1234', 'meng': '1234', 'mi': '1234',
    'mian': '1234', 'miao': '1234', 'mie': '1234', 'min': '1234', 'ming': '1234',
    'miu': '1234', 'mo': '1234', 'mou': '124', 'mu': '1234', 'muo': '3',
    'na': '1234', 'nai': '1234', 'nan': '1234', 'nang': '1234', 'nao': '1234',
    'ne': '1234', 'nei': '1234', 'nen': '1234', 'neng': '1234', 'ni': '1234',
    'nia': '1234', 'nian': '1234', 'niang': '234', 'niao': '1234', 'nie': '1234',
    'nin': '1234', 'ning': '1234', 'niu': '1234', 'nong': '1234', 'nou': '1234',
    'nu': '1234', 'nuan': '1234', 'nue': '1', 'nun': '1234', 'nuo': '234',
    'nuu': '1234', 'nuue': '234',
    'ou': '1234',
    'pa': '1234', 'pai': '1234', 'pan': '1234', 'pang': '1234', 'pao': '1234',
    'pei': '1234', 'pen': '1234', 'peng': '1234', 'pi': '1234', 'pian': '1234',
    'piao': '1234', 'pie': '1234', 'pin': '1234', 'ping': '1234', 'po': '1234',
    'pou': '1234', 'pu': '1234',
    'qi': '1234', 'qia': '1234', 'qian': '1234', 'qiang': '1234', 'qiao': '1234',
    'qie': '1234', 'qin': '1234', 'qing': '1234', 'qiong': '1234', 'qiu': '1234',
    'qu': '1234', 'quan': '1234', 'que': '1234', 'qun': '1234',
    'ran': '1234', 'rang': '1234', 'rao': '1234', 're': '1234', 'rei': '1',
    'ren': '1234', 'reng': '1234', 'ri': '1234', 'rong': '1234', 'rou': '1234',
    'ru': '1234', 'ruan': '1234', 'rui': '234', 'run': '1234', 'ruo': '1234',
    'sa': '1234', 'sai': '1234', 'san': '1234', 'sang': '124', 'sao': '1234',
    'se': '1234', 'sei': '1234', 'sen': '1234', 'seng': '1234', 'sha': '1234',
    'shai': '1234', 'shan': '1234', 'shang': '1234', 'shao': '1234', 'she': '1234',
    'shei': '1234', 'shen': '1234', 'sheng': '1234', 'shi': '1234', 'shong': '1234',
    'shou': '1234', 'shu': '1234', 'shua': '1234', 'shuai': '1234', 'shuan': '1234',
    'shuang': '1234', 'shui': '1234', 'shun': '1234', 'shuo': '1234', 'si': '1234',
    'song': '1234', 'sou': '1234', 'su': '1234', 'suan': '1234', 'sui': '1234',
    'sun': '1234', 'suo': '1234',
    'ta': '1234', 'tai': '1234', 'tan': '1234', 'tang': '1234', 'tao': '1234',
    'te': '1234', 'teng': '1234', 'ti': '1234', 'tian': '1234', 'tiao': '1234',
    'tie': '1234', 'ting': '1234', 'tong': '1234', 'tou': '1234', 'tu': '1234',
    'tuan': '1234', 'tui': '1234', 'tun': '1234', 'tuo': '1234',
    'wa': '1234', 'wai': '1234', 'wan': '1234', 'wang': '1234', 'wei': '1234',
    'wen': '1234', 'weng': '1234', 'wo': '1234', 'wu': '1234',
    'xi': '1234', 'xia': '1234', 'xian': '1234', 'xiang': '134', 'xiao': '1234',
    'xie': '1234', 'xin': '124', 'xing': '1234', 'xiong': '1234', 'xiu': '234',
    'xu': '1234', 'xuan': '1234', 'xue': '1234', 'xun': '1234',
    'ya': '1234', 'yan': '1234', 'yang': '1234', 'yao': '1234', 'ye': '1234',
    'yi': '1234', 'yin': '1234', 'ying': '1234', 'yong': '1234', 'you': '1234',
    'yu': '1234', 'yuan': '1234', 'yue': '1234', 'yun': '1234',
    'za': '1234', 'zai': '134', 'zan': '1234', 'zang': '1234', 'zao': '1234',
    'ze': '1234', 'zei': '1234', 'zen': '1234', 'zeng': '1234', 'zha': '1234',
    'zhai': '123', 'zhan': '234', 'zhang': '1234', 'zhao': '1234', 'zhe': '1234',
    'zhei': '1234', 'zhen': '1234', 'zheng': '1234', 'zhi': '1234', 'zhong': '1234',
    'zhou': '1234', 'zhu': '1234', 'zhua': '1234', 'zhuai': '1234', 'zhuan': '1234',
    'zhuang': '1234', 'zhui': '1234', 'zhun': '1234', 'zhuo': '1234', 'zi': '1234',
    'zong': '1234', 'zou': '1234', 'zu': '1234', 'zuan': '1234', 'zui': '1234',
    'zun': '1234', 'zuo': '1234'
};

// Build flat list of valid pinyin+tone combos
const VALID_COMBOS = [];
for (const [pinyin, tones] of Object.entries(SYLLABLE_TONES)) {
    for (const tone of tones) {
        VALID_COMBOS.push({ pinyin, tone: parseInt(tone) });
    }
}

const AUDIO_BASE_URL = 'https://raw.githubusercontent.com/davinfifield/mp3-chinese-pinyin-sound/master/mp3/';

// Pinyin chart structure - initials and finals
const INITIALS = ['', 'b', 'p', 'm', 'f', 'd', 't', 'n', 'l', 'g', 'k', 'h', 'j', 'q', 'x', 'zh', 'ch', 'sh', 'r', 'z', 'c', 's', 'y', 'w'];
const FINALS = ['a', 'o', 'e', 'i', 'u', 'ü', 'ai', 'ei', 'ao', 'ou', 'an', 'en', 'ang', 'eng', 'ong', 'er',
    'ia', 'ie', 'iao', 'iu', 'ian', 'in', 'iang', 'ing', 'iong',
    'ua', 'uo', 'uai', 'ui', 'uan', 'un', 'uang', 'ueng',
    'üe', 'üan', 'ün'];

// Tone marks for each vowel
const TONE_MARKS = {
    'a': ['ā', 'á', 'ǎ', 'à'],
    'e': ['ē', 'é', 'ě', 'è'],
    'i': ['ī', 'í', 'ǐ', 'ì'],
    'o': ['ō', 'ó', 'ǒ', 'ò'],
    'u': ['ū', 'ú', 'ǔ', 'ù'],
    'ü': ['ǖ', 'ǘ', 'ǚ', 'ǜ'],
};

// Streak milestones and messages
const STREAK_MESSAGES = {
    3: "Good start!",
    5: "Nice streak!",
    10: "You're on fire!",
    15: "Unstoppable!",
    20: "Tone master!",
    25: "Incredible!",
    30: "Legendary!",
    50: "Absolutely insane!",
    75: "Are you even human?!",
    100: "Tone god achieved!"
};
